# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'src/*.csproj'
    feedsToUse: 'select'
  displayName: 'dotnet restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/*.csproj'
  displayName: 'dotnet build'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'tests/*.csproj'
    feedsToUse: 'select'
  displayName: 'dotnet test restore'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'